name: holamundo
services:
  - name: web
    environment_slug: html
    github:
      repo: mariofilian/Hola-mundo  # Reemplaza con tu repo real
      branch: main
      deploy_on_push: true
    source_dir: /
    routes:
      - path: /
