name: static-site
services:
  - name: web
    environment_slug: html
    github:
      repo: MarioFilian/Hola-mundo
    github:
      branch: main
      deploy_on_push: true
    static_sites:
      - name: web
        github:
          branch: main
          deploy_on_push: true
        source_dir: /
        routes:
          - path: /
