name: Deploy to DigitalOcean App Platform

on:
 push:
   branches: [main]

permissions:
  contents: read, write
jobs:
 deploy-app:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Deploy the app
       uses: digitalocean/app_action@v2
       with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
         app_spec_location: .do/app.yaml