name: Update App

on:
 push:
   branches: 
    - main

jobs:
 deploy-app:
   name: Deploy
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Deploy the app
       uses: digitalocean/app_action/deploy@v2
       with:
         token: ${{ secrets.DIGITALOCEAN }}
         app_spec_location: .do/app.yaml
